export const userConstants = {
    USER_REQUEST: 'USER_REQUEST',
    USER_REQUEST_SUCCESS: 'USER_REQUEST_SUCCESS',
    USER_REQUEST_FAILURE: 'USER_REQUEST_FAILURE',

    USER_CREATE_REQUEST: 'USER_CREATE_REQUEST',
    USER_CREATE_REQUEST_SUCCESS: 'USER_CREATE_REQUEST_SUCCESS',
    USER_CREATE_REQUEST_FAILURE: 'USER_CREATE_REQUEST_FAILURE',

    USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
    USER_UPDATE_REQUEST_SUCCESS: 'USER_UPDATE_REQUEST_SUCCESS',
    USER_UPDATE_REQUEST_FAILURE: 'USER_UPDATE_REQUEST_FAILURE',

    USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
    USER_DELETE_REQUEST_SUCCESS: 'USER_DELETE_REQUEST_SUCCESS',
    USER_DELETE_REQUEST_FAILURE: 'USER_DELETE_REQUEST_FAILURE',
};
